# As far as I know, only the java11 runtime supports executable JAR files.
runtime: java11

# The F1 instance class doesn't have enough memory to run a Clojure project
# (even one as minimal as this), so we have to use at least an F2.
#
# If you try using F1, you're likely to bang your head against the wall trying
# to figure out why you keep getting intermittent 500 errors, until you realize
# you need to drill down into the logs in the Stackdriver Logs Viewer and find
# this error:
#
#    Exceeded soft memory limit of 256 MB with 260 MB after servicing 0 requests
#    total. Consider setting a larger instance class in app.yaml.
instance_class: F2
